services:
    netgen.ibexa_forms.form.type.fieldtype.ezuser_create:
        class: Netgen\Bundle\IbexaFormsBundle\Form\Type\FieldType\UserCreateType
        tags:
            - { name: form.type, alias: ibexa_forms_ezuser_create }

    netgen.ibexa_forms.form.type.fieldtype.ezuser_update:
        class: Netgen\Bundle\IbexaFormsBundle\Form\Type\FieldType\UserUpdateType
        tags:
            - { name: form.type, alias: ibexa_forms_ezuser_update }
