services:
    netgen.ibexa_forms.form.fieldtype_handler.ezimage:
        class: Netgen\Bundle\IbexaFormsBundle\Form\FieldTypeHandler\Image
        tags:
            - { name: netgen.ibexa_forms.form.fieldtype_handler, alias: ezimage }

    netgen.ibexa_forms.form.fieldtype_handler.ezstring:
        class: Netgen\Bundle\IbexaFormsBundle\Form\FieldTypeHandler\TextLine
        tags:
            - { name: netgen.ibexa_forms.form.fieldtype_handler, alias: ezstring }

    netgen.ibexa_forms.form.fieldtype_handler.eztext:
        class: Netgen\Bundle\IbexaFormsBundle\Form\FieldTypeHandler\TextBlock
        tags:
            - { name: netgen.ibexa_forms.form.fieldtype_handler, alias: eztext }

    netgen.ibexa_forms.form.fieldtype_handler.ezuser:
        class: Netgen\Bundle\IbexaFormsBundle\Form\FieldTypeHandler\User
        tags:
            - { name: netgen.ibexa_forms.form.fieldtype_handler, alias: ezuser }

    netgen.ibexa_forms.form.fieldtype_handler.ezemail:
        class: Netgen\Bundle\IbexaFormsBundle\Form\FieldTypeHandler\Email
        tags:
            - { name: netgen.ibexa_forms.form.fieldtype_handler, alias: ezemail }

    netgen.ibexa_forms.form.fieldtype_handler.ezselection:
        class: Netgen\Bundle\IbexaFormsBundle\Form\FieldTypeHandler\Selection
        tags:
            - { name: netgen.ibexa_forms.form.fieldtype_handler, alias: ezselection }

    netgen.ibexa_forms.form.fieldtype_handler.ezboolean:
        class: Netgen\Bundle\IbexaFormsBundle\Form\FieldTypeHandler\Checkbox
        arguments: [ "@Ibexa\\Core\\Helper\\FieldHelper" ]
        tags:
            - { name: netgen.ibexa_forms.form.fieldtype_handler, alias: ezboolean }

    netgen.ibexa_forms.form.fieldtype_handler.ezdate:
        class: Netgen\Bundle\IbexaFormsBundle\Form\FieldTypeHandler\Date
        tags:
            - { name: netgen.ibexa_forms.form.fieldtype_handler, alias: ezdate }

    netgen.ibexa_forms.form.fieldtype_handler.ezdatetime:
        class: Netgen\Bundle\IbexaFormsBundle\Form\FieldTypeHandler\DateAndTime
        tags:
            - { name: netgen.ibexa_forms.form.fieldtype_handler, alias: ezdatetime }

    netgen.ibexa_forms.form.fieldtype_handler.ezinteger:
        class: Netgen\Bundle\IbexaFormsBundle\Form\FieldTypeHandler\IntegerHandler
        arguments: [ "@Ibexa\\Core\\Helper\\FieldHelper" ]
        tags:
            - {name: netgen.ibexa_forms.form.fieldtype_handler, alias: ezinteger}

    netgen.ibexa_forms.form.fieldtype_handler.ezfloat:
        class: Netgen\Bundle\IbexaFormsBundle\Form\FieldTypeHandler\FloatHandler
        arguments: [ "@Ibexa\\Core\\Helper\\FieldHelper" ]
        tags:
            - { name: netgen.ibexa_forms.form.fieldtype_handler, alias: ezfloat }

    netgen.ibexa_forms.form.fieldtype_handler.ezurl:
        class: Netgen\Bundle\IbexaFormsBundle\Form\FieldTypeHandler\Url
        tags:
            - { name: netgen.ibexa_forms.form.fieldtype_handler, alias: ezurl }

    netgen.ibexa_forms.form.fieldtype_handler.ezcountry:
        class: Netgen\Bundle\IbexaFormsBundle\Form\FieldTypeHandler\Country
        arguments:
            - "%ibexa.field_type.country.data%"
        tags:
            - { name: netgen.ibexa_forms.form.fieldtype_handler, alias: ezcountry }

    netgen.ibexa_forms.form.fieldtype_handler.eztime:
        class: Netgen\Bundle\IbexaFormsBundle\Form\FieldTypeHandler\Time
        tags:
            - { name: netgen.ibexa_forms.form.fieldtype_handler, alias: eztime }

    netgen.ibexa_forms.form.fieldtype_handler.ezisbn:
        class: Netgen\Bundle\IbexaFormsBundle\Form\FieldTypeHandler\Isbn
        tags:
            - { name: netgen.ibexa_forms.form.fieldtype_handler, alias: ezisbn }

    netgen.ibexa_forms.form.fieldtype_handler.ezbinaryfile:
        class: Netgen\Bundle\IbexaFormsBundle\Form\FieldTypeHandler\BinaryFile
        tags:
            - { name: netgen.ibexa_forms.form.fieldtype_handler, alias: ezbinaryfile }

    netgen.ibexa_forms.form.fieldtype_handler.ezgmaplocation:
        class: Netgen\Bundle\IbexaFormsBundle\Form\FieldTypeHandler\MapLocation
        tags:
            - { name: netgen.ibexa_forms.form.fieldtype_handler, alias: ezgmaplocation }

    netgen.ibexa_forms.form.fieldtype_handler.ezobjectrelation:
        class: Netgen\Bundle\IbexaFormsBundle\Form\FieldTypeHandler\Relation
        arguments:
          - "@ibexa.api.repository"
        tags:
            - { name: netgen.ibexa_forms.form.fieldtype_handler, alias: ezobjectrelation }

    netgen.ibexa_forms.form.fieldtype_handler.ezobjectrelationlist:
        class: Netgen\Bundle\IbexaFormsBundle\Form\FieldTypeHandler\RelationList
        arguments:
          - "@ibexa.api.repository"
        tags:
            - { name: netgen.ibexa_forms.form.fieldtype_handler, alias: ezobjectrelationlist }
